Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.front.urls')),
    path('dashboard/', include('main.dashboard.urls')),
    path('auth/', include('main.auth.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/front/urls.py
from django.urls import path
from . import views


app_name = 'front'


urlpatterns = [
    path('', views.index, name='index'),
    path('product/<str:code>', views.product_detail, name='product_detail'),
    path('category/<str:code>', views.product_list, name='product_list'),
    path('carts', views.carts, name='carts'),
    path('cart/<str:code>/', views.cart_detail, name='cart_detail'),
    path('active/cart', views.active_cart, name='active_cart'),
    path('product_delete/<int:id>/',views.product_delete, name='product_delete'),

]

main/front/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from main import models

def index(request):
    categories = models.Category.objects.all()
    products = models.Product.objects.all()
    reviews = models.Review.objects.all()
    mark = 0
    for i in reviews:
        mark += i.mark
    
    mark = int(mark/len(reviews)) if reviews else 0

    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        product = models.Product.objects.get(id=product_id)
        cart = models.Cart.objects.filter(is_active=True)
        is_product = models.CartProduct.objects.filter(product=product,cart__is_active=True).first()
        if is_product:
            is_product.count += 1
            is_product.save()
            return redirect('front:active_cart')
        if not cart:
            cart = models.Cart.objects.create(
                user=request.user,
                is_active=True
            )
        
        models.CartProduct.objects.create(
            product=product,
            cart=cart.first(),
            count=1
        )
        return redirect('front:active_cart')

    context = {
        'categories':categories,
        'products':products,
        'rating':range(1,6),
        'mark':mark,
        }
    return render(request, 'front/index.html',context)


def product_detail(request,code):
    product = models.Product.objects.get(code=code)
    reviews = models.Review.objects.filter(product=product)
    images = models.ProductImg.objects.filter(product=product)
    mark = 0

    for i in reviews:
        mark += i.mark

    mark = int(mark/len(reviews)) if reviews else 0

    if request.method == 'POST':
        try:
            is_product = models.CartProduct.objects.get(product=product,cart__is_active=True)
            if is_product:
                is_product.count += int(request.POST.get('count'))
                is_product.save()
                return redirect('front:active_cart')
        except models.CartProduct.DoesNotExist:
            pass
        cart = models.Cart.objects.filter(is_active=True)
        if not cart:
            cart = models.Cart.objects.create(
                user=request.user,
                is_active=True
            )
        cart = models.Cart.objects.get(is_active=True)
        models.CartProduct.objects.create(
            product=product,
            cart=cart,
            count=request.POST.get('count')
        )
        return redirect('front:active_cart')

    context = {
        'product':product,
        'mark':mark,
        'rating':range(1,6),
        'images':images,
        'reviews':reviews,
    }
    return render(request, 'front/product/detail.html',context)

def product_list(request,code):
    queryset = models.Product.objects.filter(category__code=code)
    categories = models.Category.objects.all()
    
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        product = models.Product.objects.get(id=product_id)
        cart = models.Cart.objects.filter(is_active=True)
        try:
            is_product = models.CartProduct.objects.get(product=product,cart__is_active=True)
            if is_product:
                is_product.count += int(request.POST.get('count'))
                is_product.save()
                return redirect('front:active_cart')
        except models.CartProduct.DoesNotExist:
            pass
        cart = models.Cart.objects.filter(is_active=True)
        if not cart:
            cart = models.Cart.objects.create(
                user=request.user,
                is_active=True
            )
        cart = models.Cart.objects.get(is_active=True)
        models.CartProduct.objects.create(
            product=product,
            cart=cart,
            count=1
        )
        return redirect('front:active_cart')
    
    context = {
        'queryset':queryset,
        'categories':categories,
        }
    return render(request, 'front/category/product_list.html',context)


def product_delete(request,id):
    product = models.CartProduct.objects.get(id=id)
    product.delete()
    return redirect('front:active_cart')


@login_required(login_url='auth:login')
def carts(request):
    queryset = models.Cart.objects.filter(user=request.user, is_active=False)
    context = {'queryset':queryset}
    return render(request, 'front/carts/list.html', context)


@login_required(login_url='auth:login')
def active_cart(request):
    queryset , _ = models.Cart.objects.get_or_create(user=request.user, is_active=True)
    return redirect('front:cart_detail', queryset.code)


@login_required(login_url='auth:login')
def cart_detail(request, code):
    cart = models.Cart.objects.get(code=code)
    queryset = models.CartProduct.objects.filter(cart=cart)
    if request.method == 'POST':
        cart.is_active = False
        cart.save()
        data = list(request.POST.items())[1::]
        for id,value in data:
            product = models.CartProduct.objects.get(id=id)
            product.count = value
            product.save()
    context = {
        'cart': cart,
        'queryset':queryset
        }
    return render(request, 'front/carts/detail.html', context)

templates/front/carts/detail.html
{% extends 'front/base.html' %}
{% load static %}

{% block content %}
<main class="main-content">
    <div class="breadcrumb-area breadcrumb-height" data-bg-image="{% static 'front/images/breadcrumb/bg/1-1-1919x388.jpg' %}" style="background-image: url({% static 'front/images/breadcrumb/bg/1-1-1919x388.jpg' %});">
        <div class="container h-100">
            <div class="row h-100">
                <div class="col-lg-12">
                    <div class="breadcrumb-item">
                        <h2 class="breadcrumb-heading">Cart Page</h2>
                        <ul>
                            <li>
                                <a href="{% url 'front:index' %}">Home</a>
                            </li>
                            <li>Cart Page</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="cart-area section-space-y-axis-100">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <form method="post">
                        {% csrf_token %}
                        <div class="table-content table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th class="product_remove">remove</th>
                                        <th class="product-thumbnail">image</th>
                                        <th class="cart-product-name">Product</th>
                                        <th class="product-price">Unit Price</th>
                                        <th class="product-quantity">Quantity</th>
                                        <th class="product-subtotal">Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for i in queryset %}
                                    <tr>
                                        <td class="product_remove">
                                            <a href="{% url 'front:product_delete' i.id %}">
                                                <i class="pe-7s-close" data-tippy="Remove" data-tippy-inertia="true" data-tippy-animation="shift-away" data-tippy-delay="50" data-tippy-arrow="true" data-tippy-theme="sharpborder" tabindex="0"></i>
                                            </a>
                                        </td>
                                        <td class="product-thumbnail">
                                            <a href="#">
                                                <img src="{{i.product.banner_img.url}}" alt="Cart Thumbnail" style="width: 100px;">
                                            </a>
                                        </td>
                                        <td class="product-name"><a href="#">{{i.product.name}}</a></td>
                                        {% if i.product.discount_price %}
                                        <td class="product-price">
                                            <span class="amount"><s style="color: red;">{{i.product.price}}</s></span><br>
                                            <span class="amount">{{i.product.discount_price}}</span>
                                        </td>
                                        {% else %}
                                        <td class="product-price"><span class="amount">{{i.product.price}}</span></td>
                                        {% endif %}
                                        {% if cart.is_active %}
                                        <td class="quantity">
                                            <div class="cart-plus-minus">
                                                <input class="cart-plus-minus-box"  name="{{i.id}}" value="{{i.count}}" type="text">
                                                <div class="dec qtybutton">
                                                    <i class="fa fa-minus"></i>
                                                </div>
                                                <div class="inc qtybutton">
                                                    <i class="fa fa-plus"></i>
                                                </div>
                                            <div class="dec qtybutton"><i class="fa fa-minus"></i></div><div class="inc qtybutton"><i class="fa fa-plus"></i></div></div>
                                        </td>
                                        {% else %}
                                        <td class="product-subtotal"><span class="amount">{{i.count}}</span></td>
                                        {% endif %}
                                        <td class="product-subtotal"><span class="amount">{{i.price}}</span></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        {% if cart.is_active %}
                        <div class="row">
                            <div class="col-12">
                                <div class="coupon-all">
                                    <div class="coupon2">
                                        <button type="submit" class="btn btn-dark"> Savatga solish </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        <div class="row">
                            <div class="col-md-5 ml-auto">
                                <div class="cart-page-total">
                                    <h2>Cart totals</h2>
                                    <ul>
                                        <li>Subtotal <span>{{cart.price}}</span></li>
                                        <li>Total <span>{{cart.total_price}}</span></li>
                                    </ul>
                                    <a href="#">Proceed to checkout</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}
    

templates/front/carts/list.html
{% extends 'front/base.html' %}
{% load static %}

{% block content %}
            <!-- Begin Main Content Area -->
            <main class="main-content">
                <div class="breadcrumb-area breadcrumb-height" data-bg-image="{% static 'front/images/breadcrumb/bg/1-1-1919x388.jpg' %}">
                    <div class="container h-100">
                        <div class="row h-100">
                            <div class="col-lg-12">
                                <div class="breadcrumb-item">
                                    <h2 class="breadcrumb-heading">My Account Page</h2>
                                    <ul>
                                        <li>
                                            <a href="{% url 'front:index' %}">Home</a>
                                        </li>
                                        <li>My Account</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="account-page-area section-space-y-axis-100">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="tab-content myaccount-tab-content" id="account-page-tab-content">
                                    <div class="tab-content myaccount-tab-content" id="account-page-tab-content">
                                        <div class="tab-pane fade active show" id="account-orders" role="tabpanel" aria-labelledby="account-orders-tab">
                                            <div class="myaccount-orders">
                                                <h4 class="small-title">MY ORDERS</h4>
                                                <div class="table-responsive">
                                                    <table class="table table-bordered table-hover">
                                                        <tbody>
                                                            <tr>
                                                                <th>ORDER</th>
                                                                <th>DATE</th>
                                                                <th>PRICE</th>
                                                                <th>TOTAL</th>
                                                                <th></th>
                                                            </tr>
                                                            {% for q in queryset %}
                                                                <tr>
                                                                    <td><a class="account-order-id" href="#">#{{q.code}}</a></td>
                                                                    <td>{{q.order_date}}</td>
                                                                    <td>{{q.price}}</td>
                                                                    <td>{{q.total}}</td>
                                                                    <td><a href="{% url 'front:cart_detail' q.code %}" class="btn btn-dark"><span>View</span></a>
                                                                    </td>
                                                                </tr>
                                                            {% endfor %}
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
            <!-- Main Content Area End Here -->
{% endblock content %}
    