Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.front.urls')),
    path('dashboard/', include('main.dashboard.urls')),
    path('auth/', include('main.auth.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    
    path('', views.index, name='index'),
    # ------CATEGORY------------
    path('category-list', views.category_list, name='category_list'),
    path('category-create', views.category_create, name='category_create'),
    path('category-update/<str:code>/', views.category_update, name='category_update'),
    path('category-delete/<str:code>/', views.category_delete, name='category_delete'),
    # ------PRODUCT------------
    path('product-list', views.product_list, name='product_list'),
    path('product-create', views.product_create, name='product_create'),
    path('product-detail/<str:code>/', views.product_detail, name='product_detail'),
    path('product-update/<str:code>/', views.product_update, name='product_update'),
    path('product-delete/<str:code>/', views.product_delete, name='product_delete'),
    # ------PRODUCT IMG------------
    path('product-img-delete/<int:id>/', views.product_img_delete,name='product_img_delete'),
    path('product-video-delete/<int:id>/', views.product_video_delete,name='product_video_delete'),

]

main/dashboard/views.py
from django.shortcuts import render, redirect
from main import models

def index(request):
    context = {}
    return render(request, 'dashboard/index.html', context)

# ---------CATEGORY-------------


def category_list(request):
    queryset = models.Category.objects.all()
    context = {
        'queryset':queryset
        }
    return render(request, 'dashboard/category/list.html', context)


def category_create(request):
    if request.method == 'POST':
        models.Category.objects.create(
            name = request.POST['name']
        )
        return redirect('dashboard:category_list')
    return render(request, 'dashboard/category/create.html')


def category_update(request, code):
    queryset = models.Category.objects.get(code=code)
    queryset.name = request.POST['name']
    queryset.save()
    return redirect('dashboard:category_list')


def category_delete(request, code):
    queryset = models.Category.objects.get(code=code)
    queryset.delete()
    return redirect('dashboard:category_list')

# ---------PRODUCT----------------

def product_list(request):
    categories = models.Category.objects.all()
    category_code = request.GET.get('category_code')
    if category_code and category_code != '0':
        queryset = models.Product.objects.filter(category__code=category_code)
    else:
        queryset = models.Product.objects.all()
    context = {
          'queryset':queryset,
          'categories':categories,
          'category_code':category_code,
    }
    return render(request, 'dashboard/product/list.html', context)


def product_detail(request, code):
    queryset = models.Product.objects.get(code=code)
    images = models.ProductImg.objects.filter(product=queryset)
    reviews = models.Review.objects.filter(product=queryset)
    ratings = range(5,0,-1)
    videos = models.ProductVideo.objects.filter(product=queryset)
    context = {
          'queryset':queryset,
          'images':images,
          'reviews':reviews,
          'ratings':ratings,
          'videos':videos
    }
    return render(request, 'dashboard/product/detail.html', context)
    

def product_create(request):
    categorys = models.Category.objects.all()
    context = {'categorys':categorys}
    if request.method == 'POST':
        delivery = True if request.POST.get('delivery') else False
        product = models.Product.objects.create(
            category_id = request.POST.get('category_id'),
            name = request.POST.get('name'),
            body = request.POST.get('body'),
            price = request.POST.get('price'),
            banner_img = request.FILES.get('banner_img'),
            quantity = request.POST.get('quantity'),
            delivery = delivery
        )
    if request.FILES.getlist('product_img'):
        for img in request.FILES.getlist('product_img'):
            models.ProductImg.objects.create(
                product = product,
                img = img
        )
    if request.FILES.getlist('product_video'):
        for video in request.FILES.getlist('product_video'):
            models.ProductVideo.objects.create(
                product = product,
                video = video
        )
        return redirect('dashboard:product_list')
    return render(request, 'dashboard/product/create.html', context)


def product_update(request, code):

    images = models.ProductImg.objects.filter(product__code=code)
    videos = models.ProductVideo.objects.filter(product__code=code)
    categories = models.Category.objects.all()
    product = models.Product.objects.get(code=code)

    if request.method == 'POST':
        if request.FILES.get('banner_img'):
            product.banner_img = request.FILES.get('banner_img')
        delivery = True if request.POST.get('delivery') else False
        product.category_id = request.POST.get('category_id')
        product.name = request.POST.get('name')
        product.body = request.POST.get('body')
        product.price = request.POST.get('price')
        product.quantity = request.POST.get('quantity')
        product.delivery = delivery
        product.save()
    
    if request.FILES.getlist('product_img'):
        for img in request.FILES.getlist('product_img'):
            models.ProductImg.objects.create(
                product = product,
                img = img
        )
    if request.FILES.getlist('product_video'):
        for video in request.FILES.getlist('product_video'):
            models.ProductVideo.objects.create(
                product = product,
                video = video
        )
        return redirect('dashboard:product_update',product.code)
    
    context = {
          'images':images,
          'videos':videos,
          'categories':categories,
          'product':product

    }
    return render(request,'dashboard/product/update.html',context=context)

def product_delete(request, code):
    product = models.Product.objects.get(code=code)
    product.delete()
    return redirect('dashboard:product_list')

def product_img_delete(request, id):
    product_img = models.ProductImg.objects.get(id=id)
    product_img.delete()
    return redirect('dashboard:product_update',product_img.product_id)

def product_video_delete(request, id):
    product_video = models.ProductVideo.objects.get(id=id)
    product_video.delete()
    return redirect('dashboard:product_update',product_video.product_id)

templates/dashboard/product/detail.html
{% extends 'dashboard/base.html' %}

{% block content %}
<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">SHOP</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                <a class="breadcrumb-item" href="#">Maxsulotlar</a>
                <span class="breadcrumb-item active">Maxsulot</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="container">
                <div class="d-flex justify-content-around" >
                    <h2 class="font-weight-normal m-b-10">{{queryset.category.name}}</h2>
                    <h2 class="font-weight-normal m-b-10">{{queryset.name}}</h2>
                </div>
                <div class="justify-content-around">
                    <img alt="" class="img-fluid w-30" src="{{queryset.banner_img.url}}" >
                    <button type="button"  class="btn btn-danger btn-tone m-r-5" data-toggle="modal" data-target=".bd-example-modal-sm"><i class="anticon anticon-delete"></i> O`chirish</button>
                    <!-- Small modal -->
                    <div class="modal fade bd-example-modal-sm{{forloop.counter}}">
                        <div class="modal-dialog modal-sm">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title h4">{{queryset.name}}</h5>
                                    <button type="button" class="close" data-dismiss="modal">
                                        <i class="anticon anticon-close"></i>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <b>{{queryset.name}}ni o`chirmoqchimisiz?</b>
                                </div>
                                <div class="btn-group">
                                    <form method="post" action="{% url 'dashboard:product_delete' queryset.code %}">
                                        {% csrf_token %}
                                    <button type="submit" class="btn btn-primary btn-tone">Ha</button>
                                    <button class="btn btn-danger btn-tone" type="button" data-dismiss="modal">Yo`q</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="m-t-30">
                    <p>{{queryset.body}}</p>
                </div>
                <div class="d-md-flex m-t-30 align-items-center justify-content-between">
                    <div class="d-flex align-items-center m-t-10">
                        {% for i in images %}
                        <a class="m-r-5 m-b-5" href="javascript:void(0);" data-toggle="tooltip">
                            <div class="avatar avatar-image" style="width: 30px; height: 30px;">
                                <img src="{{i.img.url}}" alt="">
                            </div>
                        </a>
                        {% endfor %}
                    </div>
                    <div class="m-t-10">
                        <span class="font-weight-semibold m-r-10 m-b-5 text-dark">Qoldiq: </span>
                        <span>{{queryset.quantity}}</span>
                    </div>
                </div>
                <div class="d-flex align-items-center m-t-10">
                    {% for i in videos %}
                    <div class="card-body">
                        <video width="320" height="240" controls>
                            <source src="{{i.video.url}}" type="video/mp4">
                            Your browser does not support the video tag.
                        </video>
                    </div>
                    {% endfor %}
                </div>
                <div class="d-md-flex m-t-30 align-items-center justify-content-between">
                    <div class="m-t-10">
                        <span class="font-weight-semibold m-r-10 m-b-5 text-dark">Narx: </span>
                        {% if queryset.discount_price %}
                        <span><s>{{queryset.price}}</s></span>
                        {% else %}
                        <span>{{queryset.price}}</span>
                        {% endif %}
                     
                    </div>
                    <div class="m-t-10">
                        <span class="font-weight-semibold m-r-10 m-b-5 text-dark">Chegirmadagi narx: </span>
                        {% if queryset.discount_price %}
                        <span>{{queryset.discount_price}}</span>
                        {% else %}
                        <button class="btn btn-primary" >Mavjud emas</button>
                        {% endif %}
                    </div>
                    <div class="m-t-10">
                        <span class="font-weight-semibold m-r-10 m-b-5 text-dark">Yetkazib berish: </span>
                        {% if queryset.delivery %}
                        <button class="btn btn-primary" >Mavjud</button>
                        {% else %}
                        <button class="btn btn-danger" >Mavjud emas</button>
                        {% endif %}
                    </div>
                </div>
                <hr>
                {% if reviews %}
                <h5>Izohlar ({{reviews|length}})</h5>
                <div class="m-t-20">
                    <ul class="list-group list-group-flush">
                        {% for r in reviews %}
                        <li class="list-group-item p-h-0">
                            <div class="media m-b-15">
                                <div class="avatar avatar-image">
                                    {% if r.user.avatar %}
                                    <img src="{{r.user.avatar.url}}" alt="">
                                    {% endif %}
                                </div>
                                <div class="media-body m-l-20">
                                    <h6 class="m-b-0">
                                        <a href="" class="text-dark">{{r.user.username}}</a>
                                    </h6>
                                <div class="star-rating m-t-15">
                                    {% for i in ratings %}
                                    <input type="radio" id="star{{forloop.counter}}-{{forloop.counter}}" name="rating-{{forloop.counter}}" value="{{forloop.counter}}"  {% if i == r.mark %} checked="" {% endif %} disabled=""><label for="star{{forloop.counter}}-{{forloop.counter}}" title="{{forloop.counter}} star"></label>
                                    {% endfor %}
                                </div>
                            </div>
                            <span>{{r.text}}</span>
                        </li>
                        {% endfor %}
                    </ul> 
                </div> 
                {% endif %}
                <div class="m-t-30">
                    <nav>
                        <ul class="pagination justify-content-end">
                            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                            <li class="page-item active"><a class="page-link" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item"><a class="page-link" href="#">Next</a></li>
                        </ul>
                    </nav>
                </div>           
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/dashboard/product/list.html
{% extends 'dashboard/base.html' %}

{% block content %}


<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">SHOP</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                <a class="breadcrumb-item" href="#">Product</a>
                <span class="breadcrumb-item active">Ro`yxat</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-around">
            <h4>Productlar ro`yxat</h4>
            <div>
                <form class="input-group input-group-sm mb-3">
                    <select name="category_code" class="form-control">
                        <option value="0">Barchasi</option>
                        {% for category in categories %}
                        <option value="{{category.code}}" {% if category.code == category_code %} selected {% endif %}>{{category}}</option>
                        {% endfor %}
                    </select>
                    <div class="input-group-prepend">
                        <button class="input-group-text" id="inputGroup-sizing-sm" type="submit">Filterlash</button>
                    </div>
                </form>
            </div>
            </div>
            <div class="m-t-25">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Category</th>
                                <th scope="col">Nom</th>
                                <th scope="col">Harakatlar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for q in queryset %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{q.category.name}}</td>
                                <td>{{q.name}}</td>
                                <td>
                                    <a href="{% url 'dashboard:product_detail' q.code %}" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                        <i class="anticon anticon-eye"></i>
                                    </a>
                                    <a href="{% url 'dashboard:product_update' q.code %}" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                        <i class="anticon anticon-edit"></i>
                                    </a>
                                    <button type="button" class="btn btn-icon btn-hover btn-sm btn-rounded" data-toggle="modal" data-target=".bd-example-modal-sm{{forloop.counter}}">
                                        <i class="anticon anticon-delete"></i>
                                    </button>
                                    <div class="modal fade bd-example-modal-sm{{forloop.counter}}">
                                        <div class="modal-dialog modal-sm">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title h4">{{q.name}}</h5>
                                                    <button type="button" class="close" data-dismiss="modal">
                                                        <i class="anticon anticon-close"></i>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <b>{{q.name}}ni o`chirmoqchimisiz?</b>
                                                </div>
                                                <div class="btn-group">
                                                    <form method="post" action="{% url 'dashboard:product_delete' q.code %}">
                                                        {% csrf_token %}
                                                    <button type="submit" class="btn btn-primary btn-tone">Ha</button>
                                                    <button class="btn btn-danger btn-tone" type="button" data-dismiss="modal">Yo`q</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/dashboard/product/update.html
{% extends 'dashboard/base.html' %}

{% block content %}

                
    <!-- Content Wrapper START -->
    <div class="main-content">
        <div class="page-header">
            <h2 class="header-title">SHOP</h2>
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                    <a class="breadcrumb-item" href="#">Products</a>
                    <span class="breadcrumb-item active">O`zgartirish</span>
                </nav>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h4>Productni o`zgartirish</h4>
                <div class="m-t-25" style="max-width: 700px">
                    <form method="post" enctype="multipart/form-data">{% csrf_token %}
                        <div class="form-group row">
                            <label for="inputPassword3" class="col-sm-2 col-form-label">Nom</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="inputPassword3" value="{{product.name}}" name="name" >
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputPassword3" class="col-sm-2 col-form-label">Category</label>
                            <div class="col-sm-10">
                                <select name="category_id" class="form-control">
                                    {% for c in categories %}
                                        {% if c == product.category %}
                                        <option value="{{c.code}}" selected>{{c.name}}</option>
                                        {% else %}
                                        <option value="{{c.code}}">{{c.name}}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputPassword3" class="col-sm-2 col-form-label">Narx</label>
                            <div class="col-sm-10">
                                <input type="number" class="form-control" id="inputPassword3" value="{{product.price}}" name="price">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputPassword3" class="col-sm-2 col-form-label">Son/Miqdor</label>
                            <div class="col-sm-10">
                                <input type="number" class="form-control" id="inputPassword3" value="{{product.quantity}}" name="quantity">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputPassword3" class="col-sm-2 col-form-label">Yetkazib berish</label>
                            <div class="col-sm-10">                                
                                <input type="checkbox" id="inputPassword3" placeholder="..." name="delivery" {% if product.delivery %} checked {% endif %}>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputPassword3" class="col-sm-2 col-form-label">Batafsil</label>
                            <div class="col-sm-10">
                                <textarea name="body" class="form-control" cols="30" rows="10">{{product.body}}</textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputPassword3" class="col-sm-2 col-form-label">Banner rasm</label>
                            <div class="col-sm-10">
                                <input type="file" class="form-control" id="inputPassword3" name="banner_img">
                            </div>
                        </div>                        
                        <div class="form-group row">
                            <label for="inputPassword3" class="col-sm-2 col-form-label">Product rasmlar</label>
                            <div class="col-sm-10">
                                <input type="file" class="form-control" id="inputPassword3" name="product_img" multiple>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="inputPassword3" class="col-sm-2 col-form-label">Product videolar</label>
                            <div class="col-sm-10">
                                <input type="file" class="form-control" id="inputPassword3" name="product_video" multiple>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Saqlash</button>
                            </div>
                        </div>
                    </form>
                    <div class="form-group row">
                        <div class="col-sm-2 col-form-label">Rasmlar</div>
                        {% for image in images %}
                        <img src="{{image.img.url}}" alt="" height="100px">
                        <button type="button" class="btn btn-icon btn-hover btn-sm btn-rounded btn-danger" data-toggle="modal" data-target=".bd-example-modal-sm{{forloop.counter}}">
                            <i class="anticon anticon-delete"></i>
                        </button>
                        <div class="modal fade bd-example-modal-sm{{forloop.counter}}">
                            <div class="modal-dialog modal-sm">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title h4">{{image}}</h5>
                                        <button type="button" class="close" data-dismiss="modal">
                                            <i class="anticon anticon-close"></i>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <b>{{image.img}} ni o`chirmoqchimisiz?</b>
                                    </div>
                                    <div class="btn-group">
                                        <form method="post" action="{% url 'dashboard:product_img_delete' image.id %}">
                                            {% csrf_token %}
                                        <button type="submit" class="btn btn-primary btn-tone">Ha</button>
                                        <button class="btn btn-danger btn-tone" type="button" data-dismiss="modal">Yo`q</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-2 col-form-label">Videolar</div>
                        {% for video in videos %}
                            <video width="320" height="240" controls>
                                <source src="{{video.video.url}}" type="video/mp4">
                                Your browser does not support the video tag.
                            </video>
                        <button type="button" class="btn btn-icon btn-hover btn-sm btn-rounded btn-danger" data-toggle="modal" data-target=".bd-example-modal-sms{{forloop.counter0}}">
                            <i class="anticon anticon-delete"></i>
                        </button>
                        <div class="modal fade bd-example-modal-sms{{forloop.counter0}}">
                            <div class="modal-dialog modal-sm">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title h4">{{video.video}}</h5>
                                        <button type="button" class="close" data-dismiss="modal">
                                            <i class="anticon anticon-close"></i>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <b>{{video.video}} ni o`chirmoqchimisiz?</b>
                                    </div>
                                    <div class="btn-group">
                                        <form action="{% url 'dashboard:product_video_delete' video.id %}">
                                            {% csrf_token %}
                                        <button type="submit" class="btn btn-primary btn-tone">Ha</button>
                                        <button class="btn btn-danger btn-tone" type="button" data-dismiss="modal">Yo`q</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Content Wrapper END -->


{% endblock %}